Home/footer
AmineBaray/tour-trek-internship pull request #11
Opened 2024-05-21 16:28 UTC by fatimzzahra

add text

2024-05-21 16:46 UTC, ridabensalem requested changes
Hi @fatimzzahra @AmineBaray @MustaphaJAM Hi Team, 

Good job so far. !
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights
- Very beautiful UI
- no linters error
- tests working properly

## Required Changes ♻️
* You really did a great job but there are some features you need to improve

- [ ] Please make sure to fix the MIT license link at the bottom of your Readme file
- [ ] Please check the comments below 

_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-05-21 16:46 UTC, ridabensalem commented on Home/home.html
> +                  <p>blabla</p>
Hello team , well done on working on creating the nav and footer section , however I can see that "blabla" text has no meaning it is better to always use significant terms , but overall good work 👍

2024-05-21 16:46 UTC, ridabensalem commented on Home/home.html
> +      <!-- Main Block -->
Good that you used comments

2024-05-21 16:46 UTC, ridabensalem commented on Home/home.html
> +              <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
Here use a good text

2024-05-22 08:39 UTC, MustaphaJAM requested changes
Hi  @AmineBaray  @fatimzzahra  , 

Good job so far. !
There are some issues that you still need to work on to go to the next task  but you are almost there!
![mario_ladders](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)



## Highlights 
- Clean testing code 

## Required Changes ♻
* You really did a great job but there are some features you need to improve

- [ ] Please make sure to remove those repetitions and empty spaces 
- [ ] Please check it

2024-05-22 08:39 UTC, MustaphaJAM commented on Home/home.html
> -
hi team 👋,I see that we are almost done with our small project but I see her a small problem, this line is repeated, the overall is great.👌

2024-05-22 08:39 UTC, MustaphaJAM commented on Home/home.html
> +    </main>
I see that this element is repeated to </main> 👍.

2024-05-22 08:39 UTC, MustaphaJAM commented on Home/home.html
> -
this line is empty

2024-06-20 16:04 UTC, closed without merging